settings:
  permanent-lore: true
  display-worth: true
  display-price-format: "%,.2f"
  cache-expire-seconds: 300

format:
  worth-line: "<!i><#d3d3d3>Worth : <#90ee90>$<price>"
  sold: "<green>Sold <white><amount>x <item></white> for <payouts>."
  reload: "<green>BloodSells reloaded."

economy:
  provider: VAULT
  format: "$%,.2f"

items:
  DIAMOND:
    worth: 500
  EMERALD:
    worth: 250
  NETHER_STAR:
    worth: 1000
  SPAWNER:
    worth: 5000

blacklist:
  - AIR
  - BEDROCK
  - BARRIER
  - COMMAND_BLOCK
  - CHAIN_COMMAND_BLOCK
  - REPEATING_COMMAND_BLOCK
  - STRUCTURE_BLOCK
  - STRUCTURE_VOID
  - DEBUG_STICK
  - SPAWNER
  - TRIAL_SPAWNER
  - VAULT

gui:
  title: "<dark_red>BloodSells"
  size: 54
  cancel-slot: 45
  confirm-slot: 53
  cancel-material: RED_WOOL
  confirm-material: LIME_WOOL
