name: BloodSells
version: ${project.version}
main: dev.bloodworth.bloodsells.BloodSellsPlugin
api-version: '1.21'
author: BloodWorth
description: Simple Vault item worth and selling system.
softdepend:
  - Vault
permissions:
  bloodsells.use:
    default: true
  bloodsells.sellhand:
    default: true
  bloodsells.sellgui:
    default: true
  bloodsells.sellall:
    default: true
  bloodsells.sellhandall:
    default: true
  bloodsells.admin:
    default: op
  bloodsells.reload:
    default: op
  bloodsells.worth.set:
    default: op
  bloodsells.worth.info:
    default: op
